---
kind: pipeline
type: docker
name: argosbuild

platform:
  os: linux
  arch: amd64

steps:
- name: check license
  image: rabobanknl/argos-build:latest
  commands:
  - mvn license:check

- name: build argos tomcat image
  image: plugins/docker
  settings:
    context: .
    repo: argosnotary/xld-tomcat-target
    auto_tag: true
    password:
      from_secret: docker_login_token
    username:
      from_secret: docker_login_user

trigger:
  event:
  - tag
